name: Release
run-name: Release ${{ inputs.tag }} ${{ inputs.ref }}
on:
  # push:
  #   branches:
  #     - 'ci/**'
  workflow_dispatch:
    inputs:
      tag:
        description: "tag"
        required: true
      ref:
        description: "Released (branch, tag or SHA)"
        required: false
        default: ""
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      
      - run: echo "BASE_VERSION=$(git rev-parse HEAD)" >> "$GITHUB_ENV"

      - run: gh auth setup-git
        env: 
          GITHUB_TOKEN: ${{ github.token }}
      
      - run: echo $GITHUB_ENV

      - run: git config user.name "github-actions[bot]"

      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"